const productos = [
    {
        id: 1,
        direcc: "./vistas/celulares_apple.html",
        nombre: "iPhone 16 Pro Max 256GB Titanio Natural",
        precio: 5.499,
        codigo: "134389",
        precio_reg: "7,599.00",
        imagen: "./imagenes/productos/celulares/apple/iphone16_pro_max_01.webp",
        cantidad: "4",
    },
    {
        id: 2,
        direcc: "./vistas/audio.html",
        nombre: "Audífonos Sony inalámbricos WH-1000XM6-B Negro",
        precio: 1.599,
        codigo: "136688",
        precio_reg: "1,699.00",
        imagen: "./imagenes/productos/audio/wh-1000xm6-b_01.webp",
        cantidad: "7",
    },
    {
        id: 3,
        direcc: "./vistas/celulares_samsung.html",
        nombre: "Celular Samsung Galaxy S25+ 6.7'' 256GB 12GB RAM SILVER SHADOW",
        precio: 4.169,
        codigo: "135169",
        precio_reg: "1,699.00",
        imagen: "./imagenes/productos/celulares/samsung/135169_2_01.webp",
        cantidad: "8",
    },
    {
        id: 4,
        direcc: "./vistas/cocina.html",
        nombre: "Cocina Indurama CPI-3595N Smart Black Steel 5 quemadores",
        precio: 3.299,
        codigo: "136713",
        precio_reg: "1,699.00",
        imagen: "./imagenes/productos/cocina/cpi-3595n_01.webp",
        cantidad: "3",
    },
    {
        id: 5,
        direcc: "./vistas/congelador.html",
        nombre: "Congeladora Electrolux EFCC25C2HUW 251L",
        precio: 3.299,
        codigo: "125491",
        precio_reg: "1,699.00",
        imagen: "./imagenes/productos/congelador/efcc25c2huw_2_01.webp",
        cantidad: "4",
    },
    {
        id: 6,
        direcc: "./vistas/laptop.html",
        nombre: "Laptop Gamer HP Victus 15 de 15.6''",
        precio: 2.799,
        codigo: "132894",
        precio_reg: "1,699.00",
        imagen: "./imagenes/productos/laptop/a14ldla_2imagenprincipalsintexto_b_01_.webp",
        cantidad: "6",
    },
    {
        id: 7,
        direcc: "./vistas/lavadora.html",
        nombre: "Lavadora Samsung Bespoke AI",
        precio: 3.299,
        codigo: "136608",
        precio_reg: "1,699.00",
        imagen: "./imagenes/productos/lavadora/136608_01.webp",
        cantidad: "3",
    },
    {
        id: 8,
        direcc: "./vistas/licuadora.html",
        nombre: "Licuadora ActiveSense Oster BLSTTDGRBG 2L",
        precio: 849,
        codigo: "136608",
        precio_reg: "1,699.00",
        imagen: "./imagenes/productos/licuadora/120637_1_01.webp",
        cantidad: "9",
    },
    {
        id: 9,
        direcc: "./vistas/microondas.html",
        nombre: "Horno Microondas Oster POGYME1502G 45L",
        precio: 1.599,
        codigo: "127951",
        precio_reg: "1,699.00",
        imagen: "./imagenes/productos/microondas/pogyme1502g-perfil-_01.webp",
        cantidad: "6",
    },
    {
        id: 10,
        direcc: "./vistas/refri.html",
        nombre: "Refrigeradora LG Top Freezer",
        precio: 3.169,
        codigo: "130200",
        precio_reg: "1,699.00",
        imagen: "./imagenes/productos/refri/130200_01.webp",
        cantidad: "3",
    },
    {
        id: 11,
        direcc: "./vistas/relojes.html",
        nombre: "Smartwatch Huawei Watch GT 6 Pro 46mm Black",
        precio: 969,
        codigo: "137490",
        precio_reg: "1,699.00",
        imagen: "./imagenes/productos/relojes/137490_01.webp",
        cantidad: "7",
    },
    {
        id: 12,
        direcc: "./vistas/tv.html",
        nombre: "Televisor Samsung Smart TV 65''",
        precio: 4.199,
        codigo: "136439",
        precio_reg: "1,699.00",
        imagen: "./imagenes/productos/tv/136439_01.webp",
        cantidad: "2",
    }
];